### PR TITLE
system.prop: add tweaks

### PR DESCRIPTION
**Pull request by xdevs23**
Please merge this to apply great tweaks! I use them always and they are great.

### CODE REVIEW

**Comment by regalstreak** [comment]
We dont even have a build yet bru :3

**Comment by xdevs23** [comment]
Merge it tho :D

**Comment by regalstreak** [comment]
not without testing them in the build

**Comment by xdevs23** [comment]
They work on any rom and any device lol. But these tweaks are specially for OP2. Works on any rom tho.  Even on KitKat but also on latest MM.

**Comment by regalstreak** [comment]
err create this on rr branch too @xdevs23 plz

**Comment by regalstreak** [comment]
@xdevs23 my mistake. Had thought this was on rr-6.0 branch
Need it there. We will cherry-pick this later on XOS
Btw I have rebased it and removed this commit for now :+1:

**Comment by xdevs23** [comment]
Nvm, just add the tweaks when XOS is working ;)

**Comment by regalstreak** [comment]
create this PR for the rr branch plz

**Comment by xdevs23** [comment]
k

**Comment by regalstreak** [comment]
thanks (y)

**Comment by xdevs23** [comment]
np

**Pull request merged**
